---
title: "Quadratic Models"
subtitle: "Standard 2"
author: "MS-A4.2 Non-linear Relationships"
institute: ""
date: "updated: `r Sys.Date()`"
output_dir: "docs"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css:
      - my-theme.css
      - default
      - metropolis
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:10"
---
# Learning Intentions

#### Topic
**Non-linear Relationships**

#### Learning Goals
Quadratic Models

#### Success Criteria

* Construct and analyse a quadratic model to solve practical problems involving quadratic functions or expressions of the form $y=ax^2+bx+c$, for example braking distance against speed
  * graph a quadratic function with and without technology
  * interpret the turning point and intercepts of a parabola in a practical context
  * consider the range of values for $x$ and $y$ for which the quadratic model makes sense in a practical context

#### Activities/Tasks
Refer to Edmodo

---

# Starter question

Draw the graph of $y=-x^2-4x$ Use the graph the find:

a) turning point

b) axis of symmetry

c) $y$-intercept

d) $x$-intercepts

e) minimum or maximum value

---


# Quadratic Models

--

Quadratic modelling is when you use the parabolic shape of a quadratic function to imitate the shape of a real life phenomena.

--

For example, if you study physics you should have learnt about gravity. The acceleration due to gravity is $\approx9.81\ \text{m/s}^{2}$.

--

Because questions relating to gravity will have a square, quadratic functions are ideal for modelling them. 

---

# Example 1

A rock is thrown from a cliff. The height $h$ of the rock after time $t$ is given by $h=-\dfrac{1}{2}t^2+2t+6$.

a) Draw the graph of $h=-\dfrac{1}{2}t^2+2t+6$.

b) Use the graph to work out how high the cliff is.

c) Use the graph to calculate the maximum height of the rock.

d) How long is it before the rock hits the ground?

e) Use the graph to estimate the height after 4.5 seconds.

---

# Stopping Distance

Stopping distance is the distance it takes for a vehicle to stop.

--

It can be calculated given the function:

$$d=\frac{5vt}{18}+\frac{v^2}{170}$$

Where:

* $d$ is the stopping distance in metres (m)

* $v$ is the velocity (speed) of the vehicle in km/h

* $t$ is the reaction time in seconds (s)

--

Note that 

* $\dfrac{5vt}{18}$ is the reaction distance

* $\dfrac{v^2}{170}$ is the braking distance 

---

# Example 2

Jenny was driving at a speed of 80 km/h and has a reaction time of 0.7 s. Using the formula provided, calculate the stopping distance correct to the nearest metre.

$$d=\frac{5vt}{18}+\frac{v^2}{170}$$

---

# Check in question

The area of a rectangular garden bed is given by $A=4l-l^2$, where $l$ is one of the lengths in metres.

a) Draw the graph of $A=4l-l^2$

b) Use the graph to estimate the area if the given length is 2.5 metres.

c) What is the maximum area?

d) What length is required to have the maximum area?